steps:
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: [ "build", "-t", "gcr.io/$PROJECT_ID/ixnestjsapp:latest", "-t", "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/ixnestjsapp:$BUILD_ID", ".", ]
  id: "build-image-ixnestjsapp"
  waitFor: ["-"] # The '-' indicates that this step begin immediately

# Push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA"]
  id: "push-image-to-container-registery"
  waitFor: ["build-image-ixnestjsapp"] # The push start once build is done

# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run",
      "deploy",
      "ixnestjsapp",
      "--image",
      "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA",
      "--region",
      "us-west2",
      "--platform",
      "managed",
      "--allow-unauthenticated",
    ]

images:
- "gcr.io/$PROJECT_ID/ixnestjsapp:latest"
- "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA"
- "gcr.io/$PROJECT_ID/ixnestjsapp:$BUILD_ID"
