# steps:
# # Build the container image
# - name: "gcr.io/cloud-builders/docker"
#   args: [ "build", "-t", "gcr.io/$PROJECT_ID/ixnestjsapp:latest", "-t", "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/ixnestjsapp:$BUILD_ID", ".", ]
#   id: "build-image-ixnestjsapp"
#   waitFor: ["-"] # The '-' indicates that this step begin immediately

# # Push the container image to Container Registry
# - name: "gcr.io/cloud-builders/docker"
#   args: ["push", "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA"]
#   id: "push-image-to-container-registry"
#   waitFor: ["build-image-ixnestjsapp"] # The push start once build is done

# # Deploy container image to Cloud Run
# - name: "gcr.io/cloud-builders/gcloud"
#   args:
#     [
#       "run",
#       "deploy",
#       "ixnestjsapp",
#       "--image",
#       "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA",
#       "--region",
#       "us-west2",
#       "--platform",
#       "managed",
#       "--allow-unauthenticated",
#     ]

# images:
# - "gcr.io/$PROJECT_ID/ixnestjsapp:latest"
# - "gcr.io/$PROJECT_ID/ixnestjsapp:$COMMIT_SHA"
# - "gcr.io/$PROJECT_ID/ixnestjsapp:$BUILD_ID"

substitutions:
  _DOCKER_COMPOSE_VERSION: 1.28.2
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:["build","--build-arg","DOCKER_COMPOSE_VERSION=${_DOCKER_COMPOSE_VERSION}","-t","gcr.io/$PROJECT_ID/docker-compose:latest","-t","gcr.io/$PROJECT_ID/docker-compose:${_DOCKER_COMPOSE_VERSION}", ".",]
  id: "build-image-sonarcube"
  waitFor: ["-"]
# - name: 'gcr.io/$PROJECT_ID/docker-compose'
#   args: ['version']

# Push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/docker-compose:${_DOCKER_COMPOSE_VERSION}"]
  id: "push-image-to-container-registry"
  waitFor: ["build-image-sonarcube"] # The push start once build is done

# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run",
      "deploy",
      "sonarcube",
      "--image",
      "gcr.io/$PROJECT_ID/docker-compose:${_DOCKER_COMPOSE_VERSION}",
      "--region",
      "us-west2",
      "--platform",
      "managed",
      "--allow-unauthenticated",
    ]

images:
- 'gcr.io/$PROJECT_ID/docker-compose:latest'
- 'gcr.io/$PROJECT_ID/docker-compose:${_DOCKER_COMPOSE_VERSION}'
tags: ['cloud-builders-community']
